Twitch provider
supabase/gotrue pull request #131
Opened 2021-07-04 19:45 UTC by ph1p

## What kind of change does this PR introduce?

- Fixes a small bug I had when running tests. Replaces `u.Fragment` with `u.RawQuery` inside the `assertAuthorizationSuccess`method (Maybe this is only an error at my dev environment)
- Add the provider to login with a twitch account

## What is the current behavior?

No login possible with twitch account.

## What is the new behavior?

Login with twitch is now possible. 

## Additional context

- Unfortunately I couldn't use the `makeRequest` method for this feature, because I had to include the `Client-Id` in the header and couldn't find any other way except writing a custom request.
- I had to check the `scopes` variable and manually merge the scopes if they were set, because an empty `scopes` variable strangely added a `+` to the query and the request failed. 
- Info: The new twitch api always responds with a user array, so I always take the first one.

Feedback is strongly welcome! And always feel free to edit the files (:

## Links

- https://dev.twitch.tv/console/extensions/create 
- https://dev.twitch.tv/docs/authentication#scopes
- https://dev.twitch.tv/docs/authentication/getting-tokens-oauth#oauth-authorization-code-flow
- https://dev.twitch.tv/docs/api/reference#get-users

2021-07-08 15:17 UTC, kangmingtay requested changes
Hi @ph1p, thanks so much for your contribution! It's always great to see people from the community contribute a new OAuth provider monthly :)

2021-07-08 15:22 UTC, ph1p commented on hack/migrate_postgres.sh
> +export GOTRUE_DB_DATABASE_URL="postgres://postgres:root@tcp(localhost:5432)/gotrue_$DB_ENV?sslmode=disable&parseTime=true&multiStatements=true"
Ah ok :) I'll drop this commit. The thing is that I went through the "Contribution"-file and was not able to set up the postgres database connection correctly. I'l

2021-07-09 05:16 UTC, kangmingtay commented
Just nitpicking here #135 - change the struct literals used, i'd prefer for the struct receiver to be a prefix of the struct. Gonna merge it today! :)

2021-07-09 05:22 UTC, kangmingtay approved these changes

2021-07-09 05:22 UTC, closed without merging