Add Metadata to Phone Signup
supabase/gotrue pull request #506
Opened 2022-06-20 03:18 UTC by J0

## What kind of change does this PR introduce?
As in title

## What is the current behavior?

Fix #416 

## What is the new behavior?

Metadata with Passwordless phone signups 

## Additional context

We need to discuss with the client lib team whether this would make sense. Also need to validate changes.

Finally tests would need to be updated here and on GoTrue-js

2022-06-28 22:23 UTC, kangmingtay requested changes
yeah this is nice, can we also add this in for magiclinks? 

currently, i think the workaround is to call `PUT /user` to update the user metadata after a sign-in which isn't ideal because it requires an extra API call

2022-07-10 11:15 UTC, kangmingtay approved these changes

2022-07-10 11:15 UTC, kangmingtay commented
we should also try to add a test case for this

2022-07-12 05:25 UTC, J0 commented on api/magic_link.go
> +			r.ContentLength = int64(len(string(newBodyContent)))
Sad. This doesn't give the exact number of bytes. Additionally, it seems like we could potentially remove this line as per [this thread](https://stackoverflow.com/questions/49806673/how-to-know-content-length-of-my-request-body-in-order-to-add-it-in-my-request-h)

2022-07-20 09:53 UTC, merged