fix: use `delete` instead of `truncate` for fast tests
supabase/gotrue pull request #654
Opened 2022-08-30 09:00 UTC by hf

`DELETE` is faster than `TRUNCATE` when running the tests.

2022-08-30 09:28 UTC, J0 approved these changes

2022-08-30 19:01 UTC, kangmingtay requested changes

2022-08-30 19:01 UTC, kangmingtay commented on models/connection.go
> +			if err := tx.RawQuery("DELETE " + tableName + " CASCADE").Exec(); err != nil {
shouldn't it be `delete from`?

2022-08-30 19:03 UTC, kangmingtay commented
why not just revert this? (https://github.com/supabase/gotrue/pull/650/files)

2022-09-02 10:55 UTC, kangmingtay commented on models/connection.go
> +			if err := tx.RawQuery("DELETE " + tableName + " CASCADE").Exec(); err != nil {
```suggestion
			if err := tx.RawQuery("DELETE FROM " + tableName + " CASCADE").Exec(); err != nil {
```

2022-09-02 11:06 UTC, kangmingtay approved these changes

2022-09-02 11:08 UTC, merged