feat: add password security requirements
supabase/gotrue pull request #819
Opened 2022-11-18 00:12 UTC by csmith

## What kind of change does this PR introduce?

feature

## What is the current behavior?

Any password equal to or greater than the minimum length is permitted

## What is the new behavior?

Four new config settings that require at least one lowercase, uppercase, numeric and special character in the password. Trying to set a password that doesn't comply with these requirements results in a 422 error (similar to the existing behaviour for passwords that are too short).

## Additional context

This could be done in a bunch of other ways (e.g. regular expressions, some way of requiring X different sets but not necessarily caring about which ones, ...). I had a look around for other configurable password policies and the only one I could see that was clearly documented is the one for AWS IAM: https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_passwords_account-policy.html#password-policy-details

Relevant to this change is the recent decision by the French GDPR authority in relation to Discord (see https://www.cnil.fr/en/discord-inc-fined-800-000-euros):

> At the time of the online investigation, when creating an account on DISCORD, a password of six characters including letters and numbers was accepted.
> 
> The restricted committee considered that DISCORD's password management policy was not sufficiently strong and restrictive to ensure the security of users' accounts.

2022-11-18 00:46 UTC, kangmingtay requested changes
Hi @csmith, thanks for taking the time to contribute to this project through this PR! We do plan to support this behaviour, however, it won't be through the gotrue config but rather as a custom webhook for password validation. The current gotrue configuration is already pretty bloated and adding any optional configuration will just increase the overhead when it comes to configuring the service for new developers. As such, we won't be planning to merge this PR.

2022-11-18 13:06 UTC, csmith commented
Hi @kangmingtay, thanks for the reply. Do you have a rough timeline for when your alternate solution would be available?

We can't really use supabase in production in good conscience (or in compliance with the GDPR) without a way to prevent horribly insecure passwords.

2022-11-21 10:58 UTC, hf commented
> Hi @kangmingtay, thanks for the reply. Do you have a rough timeline for when your alternate solution would be available?

Webhooks are one of our top next priorities, so ideally (tho this may change) is the first half of 2023.

> We can't really use supabase in production in good conscience (or in compliance with the GDPR) without a way to prevent horribly insecure passwords.

You can enforce this on the browser side for the time being. It's actually much better to do it there as you can guide the user towards a secure password. You can also integrate with [HaveIBeenPwned](https://haveibeenpwned.com) or use libraries like [zxcvbn](https://github.com/dropbox/zxcvbn). Backend enforcement is good, but as @kangmingtay explained we plan on letting you customize this behavior using custom hooks / functions.

2024-01-12 06:10 UTC, closed without merging

2024-01-12 06:10 UTC, J0 commented
Hey @csmith,

Thanks for patiently waiting. We've recently introduced more configurability around [password security checks](https://supabase.com/docs/guides/auth/passwords) which should address the issue.

I'm going to close the PR for now but let me know if there are unresolved concerns or additional features needed.

Once again, thank you for contributing to Supabase