fix: refactor `UpdateOnly` to use `UpdateColumns` from pop
supabase/gotrue pull request #832
Opened 2022-11-24 13:53 UTC by hf

In the past `UpdateOnly` had to use a workaround, but now the [`UpdateColumns`](https://pkg.go.dev/github.com/gobuffalo/pop/v5#Connection.UpdateColumns) method is available in Pop, making the old approach unnecessary.

2022-11-24 19:15 UTC, kangmingtay requested changes

2022-11-24 19:15 UTC, kangmingtay commented on storage/sql.go
> +	return conn.UpdateColumns(model, includeColumns...)
do we always want the `updated_at` column to be updated automatically by pop? if so, we need to do the following as per the documentation:
```suggestion
        includeColumns = append(includeColumns, "updated_at")        
	return conn.UpdateColumns(model, includeColumns...)
```

if we don't then we need check where `UpdateOnly` is used and add the `updated_at` column to those that require the column to be updated

2022-11-28 07:55 UTC, J0 approved these changes

2023-03-21 03:22 UTC, kangmingtay approved these changes

2023-03-21 03:33 UTC, kangmingtay commented
closing this PR because some tables in the auth schema do not have the `updated_at` column so the only way to check is to grab all the columns and remove the included ones to get the excluded set - which is basically how the current way does it.

2023-03-21 03:33 UTC, closed without merging