Bugfix/redirect url construct
supabase/gotrue pull request #97
Opened 2021-05-16 15:58 UTC by icecream78

According to issue #90  I've implemented logic about prioritization of redirect parameter into workflow of redirect urls construction.
Now, when function getRefferer() calls - firstly checked redirect_to header/parameter, if it's empty - check referrer header, if it's empty too - return config_site value. I suppose that logic fits customers wishes.
Additionally add new configuration parameter REDIRECT_PARAM_NAME for constomization alias of redirect url into input parameters list (default is redirect_to).

2021-05-16 15:59 UTC, icecream78 commented
@awalias  need your opinion and review

2021-05-17 11:04 UTC, awalias requested changes
I think we should fix the prioritization only, and in other PRs can address the other issues 

but looks good otherwise 👍

2021-05-17 11:04 UTC, awalias commented on api/verify_test.go
> +			expectedRedirectURL: "https://someapp-something.codemagic.app/",
test cases can be:

```
		{
			desc:                "same site url and redirect url with path",
			siteURL:             "http://localhost:3000",
			uriAllowList:        []string{},
			requestRedirectURL:  "http://localhost:3000",
			expectedRedirectURL: "http://localhost:3000",
		},
		{
			desc:                "different site url and redirect url with path",
			siteURL:             "https://someapp-something.codemagic.app",
			uriAllowList:        []string{"http://localhost:3000"},
			requestRedirectURL:  "http://localhost:3000",
			expectedRedirectURL: "http://localhost:3000",
		},
		{
			desc:                "different site url and redirect url withput path",
			siteURL:             "https://someapp-something.codemagic.app",
			uriAllowList:        []string{"http://localhost:3000"},
			requestRedirectURL:  "http://localhost:3000/some/thing",
			expectedRedirectURL: "https://someapp-something.codemagic.app",
		},
		{
			desc:                "different site url and not permited redirect url",
			siteURL:             "https://someapp-something.codemagic.app",
			uriAllowList:        []string{},
			requestRedirectURL:  "https://someapp-something.codemagic.app/some/thing",
			expectedRedirectURL: "https://someapp-something.codemagic.app/some/thing",
		},
```

2021-05-17 11:04 UTC, awalias commented on conf/configuration.go
> +	RedirectParamName string                `json:"redirect_param_name" default:"redirect_to"`
I don't think we should include custom redirect param name in this PR

2021-05-17 16:21 UTC, icecream78 commented on api/verify.go
> +			if strings.HasSuffix(rurl, "#") || strings.HasSuffix(rurl, "?") || strings.HasSuffix(rurl, "/") {
I guess that it's better add this check because if url ends with / then hardcoded # char will be encoded as %23

2021-05-19 06:15 UTC, icecream78 commented
I've add fixes according to review

2021-05-26 04:35 UTC, awalias commented on api/verify.go
> +			if strings.HasSuffix(rurl, "#") || strings.HasSuffix(rurl, "?") || strings.HasSuffix(rurl, "/") {
let's fix this one in a different branch, keep this PR just for redirect fix

2021-05-26 06:43 UTC, merged